apiVersion: networking.istio.io/v1alpha3
kind: EnvoyFilter
metadata:
  name: add-prefix-filter
  namespace: default
spec:
  workloadSelector:
    labels:
      app: orders-service
  configPatches:
    - applyTo: HTTP_ROUTE
      match:
        context: SIDECAR_OUTBOUND
        routeConfiguration:
          vhost:
            name: "outbound|8080||billing-service.default.svc.cluster.local"
      patch:
        operation: MERGE
        value:
          route:
            match:
              safe_regex:
                regex: "^/api/v2/orders/[^/]+/details/[^/]+/summary.*$"
            prefix_rewrite: "/newprefix/api/v2/orders"
            route:
              cluster: "outbound|8081||billing-service.default.svc.cluster.local"
